apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tech-day-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: v1
      kind: PipelineRun 
      metadata:
        generateName: tech-day-pipelinerun-
      spec:
        pipelineRef:
          name: tech-day-pipeline
        params:
          - name: gitrevision
            value: $(tt.params.gitrevision)      
          - name: gitrepositoryurl
            value: $(tt.params.gitrepositoryurl)
        serviceAccountName: tech-day-sa
        workspaces:
          - name: shared-data
            emptyDir: {}
          - name: docker-config
            secret:
              secretName: regcred