---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  results:
    - name: output
  params:
    - name: CONTEXT
      type: string
      default: "."
    - name: ARGS
      type: string
    - name: NODE_IMAGE
      type: string
      default: "registry.access.redhat.com/ubi9/nodejs-20:latest"
  steps:
    - name: npm-run
      image: $(params.NODE_IMAGE)
      script: |
        set -e
        cd $(workspaces.source.path)/$(params.CONTEXT)
        # Execute the command and process output
        OUTPUT=$(bash -c "npm $(params.ARGS)" 2>/dev/null | tr -d '"' || echo "latest")
        echo -n "$OUTPUT" | tee $(results.output.path)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT)
      env:
        - name: CI
          value: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
